# Generated by Django 4.1.2 on 2022-10-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_vacancy_company_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
    ]
