# Generated by Django 4.1.2 on 2022-10-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_error_alter_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='data',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default={'get_parse': ''})),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='язык программирования')),
            ],
            options={
                'unique_together': {('language',)},
            },
        ),
    ]
