# Generated by Django 4.1.2 on 2022-10-27 09:35

from django.db import migrations, models
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_alter_error_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=models.JSONField(default=scraping.models.default_urls),
        ),
    ]
