# Generated by Django 4.1.5 on 2023-01-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_alter_language_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
